<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sedang</name>
   <tag></tag>
   <elementGuidId>1ad9d748-e8a3-46c8-b07d-f231348a5eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div/article/div[2]/div[4]/div[2]/div/div/nav/ul/li[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-underline px-2 text-gray-600 self-end w-full h-full button-dropdown-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
              Sedang
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;pt-12&quot;]/div[@class=&quot;mx-auto w-full max-w-xl&quot;]/div[1]/div[1]/article[@class=&quot;pt-10&quot;]/div[@class=&quot;px-4 lg:px-0&quot;]/div[@class=&quot;flex flex-col font-pt-sans mt-8 mb-8 rounded-sm text-gray-600 text-sm w-full md:flex-row md:items-center lg:items-center md:justify-between lg:px-0 max-w-xl&quot;]/div[@class=&quot;hidden md:flex&quot;]/div[@class=&quot;flex items-center mb-4 relative wrap-button pt-4 pl-4&quot;]/div[@class=&quot;flex flex-no-shrink z-auto relative md:mb-0&quot;]/nav[@class=&quot;absolute button-dropdown-child-text z-30 pt-4 left-0&quot;]/ul[@class=&quot;rounded-sm bg-white flex flex-row font-chronicle-display justify-center relative text-sm flex-wrap list-reset py-3 px-4 shadow w-full -ml-2&quot;]/li[@class=&quot;flex py-1 cursor-pointer rounded-sm hover:bg-white-citrine w-1/3 flex flex-no-shrink py-1 rounded-sm hover:bg-white-citrine&quot;]/button[@class=&quot;no-underline px-2 text-gray-600 self-end w-full h-full button-dropdown-btn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/article/div[2]/div[4]/div[2]/div/div/nav/ul/li[2]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='·'])[1]/following::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUTRI DIAH EKOWATI'])[1]/following::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin Tautan'])[2]/preceding::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tautan tersalin!'])[2]/preceding::button[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/nav/ul/li[2]/button</value>
   </webElementXpaths>
</WebElementEntity>
