<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ButtonBerlangganan</description>
   <name>ButtonBerlangganan</name>
   <tag></tag>
   <elementGuidId>c2f8bfd7-9248-4cd3-bb2e-73349d0c89f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div/div[3]/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
