<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>css_CenterContent</name>
   <tag></tag>
   <elementGuidId>eab31832-536d-4fbb-970c-445ef3ab951f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.px-4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.px-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
