<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_wa</name>
   <tag></tag>
   <elementGuidId>c6569873-8d34-4417-9080-a1c12e5fded9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div/article/div[2]/div[4]/div[2]/div[2]/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://api.whatsapp.com/send?text=Krisis%20Lingkungan%20dan%20Bencana%20Pandemi%20https://www.kompas.id/baca/opini/2021/01/14/krisis-lingkungan-dan-bencana-pandemi/%3Futm_source%3Dbebasakses_kompasid%26utm_medium%3Dwhatsapp_shared%26utm_content%3Dsosmed%26utm_campaign%3Dsharinglink</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-black flex h-6 justify-center mr-1 no-underline p-1 rounded-sm text-white w-6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;pt-12&quot;]/div[@class=&quot;mx-auto w-full max-w-xl&quot;]/div[1]/div[1]/article[@class=&quot;pt-10&quot;]/div[@class=&quot;px-4 lg:px-0&quot;]/div[@class=&quot;flex flex-col font-pt-sans mt-8 mb-8 rounded-sm text-gray-600 text-sm w-full md:flex-row md:items-center lg:items-center md:justify-between lg:px-0 max-w-xl&quot;]/div[@class=&quot;hidden md:flex&quot;]/div[@class=&quot;flex justify-end items-center&quot;]/div[@class=&quot;flex&quot;]/a[@class=&quot;bg-black flex h-6 justify-center mr-1 no-underline p-1 rounded-sm text-white w-6&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/article/div[2]/div[4]/div[2]/div[2]/div/a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='·'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUTRI DIAH EKOWATI'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin Tautan'])[2]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tautan tersalin!'])[2]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://api.whatsapp.com/send?text=Krisis%20Lingkungan%20dan%20Bencana%20Pandemi%20https://www.kompas.id/baca/opini/2021/01/14/krisis-lingkungan-dan-bencana-pandemi/%3Futm_source%3Dbebasakses_kompasid%26utm_medium%3Dwhatsapp_shared%26utm_content%3Dsosmed%26utm_campaign%3Dsharinglink')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/a[3]</value>
   </webElementXpaths>
</WebElementEntity>
